### ISSUE TITLE
Use .env value for Zone

### ISSUE THREAD

**Issue by gbowne-quickbase** [workingconcept/cloudflare-craft-plugin#25]
We can use an `.env` value for the API key or token, like $CLOUDFLARE_API_TOKEN, but we can't do that for the zone. Can this be set and pulled through for the Zone as well?

**Comment by gbowne-quickbase** [comment]
I guess I didn't see really clearly that the zone would be something I could select once my token was connected.

**Comment by mattstein** [comment]
Sorry for the confusion, Greg! My original intent to simplify zone selection [turned out to be problematic](https://github.com/workingconcept/cloudflare-craft-plugin/issues/17) for newer scope-limited tokens and people who’d rather hardcode settings.

Happy to take suggestions for documentation or setup UX!
