### ISSUE TITLE
PurgeCloudflareCache job always reports success even on API failure

### ISSUE THREAD

**Issue by jabinb** [workingconcept/cloudflare-craft-plugin#61]
## Steps to reproduce
1. Set an invalid `zoneId` or `apiToken`
2. Save an element eligible for purging
3. Queue Job will be generated
https://github.com/putyourlightson/craft-cloudflare/blob/657429d3b5d5b3959b26b703f0b5fd43d521d4e1/src/Cloudflare.php#L306
4. `Api::purgeUrls` error will get logged to `queue.log` => `URL purge failed.` either from the status code or an Exception
https://github.com/putyourlightson/craft-cloudflare/blob/657429d3b5d5b3959b26b703f0b5fd43d521d4e1/src/services/Api.php#L302-L306 https://github.com/putyourlightson/craft-cloudflare/blob/657429d3b5d5b3959b26b703f0b5fd43d521d4e1/src/services/Api.php#L359
5. Job will complete successfully, ignoring the response from `Api::purgeUrls` (`{ success: false }`), the user will have no feedback from Craft that the URLs were not purged.
https://github.com/putyourlightson/craft-cloudflare/blob/657429d3b5d5b3959b26b703f0b5fd43d521d4e1/src/queue/jobs/PurgeCloudflareCache.php#L21-L22

## What should happen
`PurgeCloudflareCache::execute` should check the success response of `Api::purgeUrls` and fail the queue job appropriately by throwing an exception.

**Comment by bencroker** [comment]
This behaviour is intentional as failed queue jobs may pause the queue and require admin intervention. Rather than doing that, failed requests to the API are logged for admins to take care of and there is no explicit reporting of success even though the queue job completes.

Apologies for the delay in responding, it turns out I had notifications disabled for this repo.
